# fly.toml app configuration file generated for home-controller on 2024-10-31T10:02:07Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'home-controller'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
